version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 8
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 500
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 100
