sudo: required
language: node_js
node_js:
  - "7"
services:
  - docker
env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
    - GH_TOKEN=$GH_TOKEN
    - GIT_COMMIT_SHA=$TRAVIS_PULL_REQUEST_SHA
    - TRAVIS_BRANCH=$TRAVIS_BRANCH
    - SURGE_LOGIN=$SURGE_LOGIN
    - SURGE_TOKEN=$SURGE_TOKEN
script:
  - make test
  - make content-assertions
  - make update-contentrc
deploy:
  provider: script
  script: make deploy 
  on:
    branch: master 
