sudo: required
language: node_js
node_js:
  - "7"
services:
  - docker
env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
    - GH_TOKEN=$GH_TOKEN
    - GIT_COMMIT_SHA=$TRAVIS_PULL_REQUEST_SHA
    - TRAVIS_BRANCH=$TRAVIS_BRANCH
script:
  - make test
  - make content_assertions
after_success:
  - test $TRAVIS_BRANCH = "master" && make update-contentrc
